### PR TITLE
Update 'Spring Boot integration'

### PR DESCRIPTION
**Pull request by Mabin-J**
Reference: line/line-bot-sdk-java@a0ce1609c5ce589513ac38d1f9d92026c45f5a4a

### CODE REVIEW

**Comment by tokuhirom** [comment]
hmm? Why do you want to revert README file?

**Comment by Mabin-J** [comment]
Oh, I'm so sorry.

But when I used exam code in current 'README.md of the root,' It didn't work.
I think that because I used a different version of 'line-bot-spring-boot'. 

I used 'line-bot-spring-boot 1.1.0' because 1.1.0 version is the latest version in mvnrepository.com.  
(http://www.mvnrepository.com/artifact/com.linecorp.bot/line-bot-spring-boot)

Example code of [README.md of the root](https://github.com/line/line-bot-sdk-java/blob/a585bbf3fe0dcf928c8887d505d5b9a57b25283b/README.md) didn't work with 'line-bot-spring-boot 1.1.0' 
but [line-bot-spring-boot/README.md](https://github.com/line/line-bot-sdk-java/blob/a585bbf3fe0dcf928c8887d505d5b9a57b25283b/line-bot-spring-boot/README.md) do work. 

So, I think that README.md of the root is not updated.

**Comment by kazuki-ma** [comment]
@Mabin-J 

Sorry for inconvenience, but current version is 1.3.0 (released in 2016-11-16) and README.md is based on it. (Actually, `@LineMessageHandler` written in README.md is introduced in 1.2.0.)

So, I think updating SDK version resolves your problem.

You can get dependency definitions samples in https://mvnrepository.com/artifact/com.linecorp.bot/line-bot-spring-boot/1.3.0.

**Comment by kazuki-ma** [comment]
Sorry, I found `README.md` in `/line-bot-spring-boot/` is not up-to-date.
(Unlike README.md in root)

Updating in https://github.com/line/line-bot-sdk-java/pull/67

**Comment by Mabin-J** [comment]
Thank you. :)

**Pull request closed without merging**
