### PR TITLE
Add type parameter in MessageEvent.

### PR DESCRIPTION
**Pull request by kazuki-ma**
I think `MessageEvent` is actually generic type.

### CODE REVIEW

**Comment by tokuhirom** [comment]
Good catch. But this patch may  break binary compatibility.

**Comment by tokuhirom** [comment]
This patch makes the code cleanly, but it may not increase usability. And it breaks backward compatibility.
I suggest to do this at next major update.

**Comment by kazuki-ma** [comment]
I agree that this patch good for next update.

But in my understand, it will not break binary compatibility.

```java
public class MessageEvent<T extends MessageContent> implements Event {
    private final T message;
}
```

will be compiled into

```java
public class MessageEvent implements Event {
    private final MessageContent message;
}
```

Test code added, and maybe good to test locally

Bad Case (Same Erasure)
```java
class Test<T> {
    Test(T value) {} // This compiled into "Test(Object value){}"
    Test(Object value) {}
}
```

Good Case (Different Erasure)
```java
class Test<T extends String> {
    Test(T value) {} // This compiled into "Test(String value){}" because T is-a String (at least).
    Test(Object value) {}
}
```

Anyway, I perfectly agree do it next version. (Could you prepare branch for next version?)

**Comment by tokuhirom** [comment]
Okay, i see. if there's no backward compatiblity issue, there's no reason to reject this patch.

**Pull request merged**
