### PR TITLE
Hides the process of parsing callback request behind LineBotClient

### PR DESCRIPTION
**Pull request by synk**
ASIS
```
final ObjectMapper objectMapper = new ObjectMapper();
objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
CallbackRequest req = objectMapper.readValue(json, CallbackRequest.class);
```
TOBE
```
CallbackRequest req = lineBotClient.readCallbackRequest(json);
```

### CODE REVIEW

**Comment by synk** [comment]
Just wondering. Why does `LineBotClient` have to accept an external `ObjectMapper ` as a parameter to build? I think we can hide it within the client and it makes things simpler.

**Comment by tokuhirom** [comment]
Hmm... I can't remember the reason. We can hide it.

**Comment by synk** [comment]
Ok. let me hide it

**Comment by krrrr38** [comment]
IMHO, LineBotClient looks a little bit heavy? It might be separated like followings.
- receiver module
  - request parser class
  - request validator class
- http client module
  - http client class

**Comment by synk** [comment]
@krrrr38 sounds good to me

**Pull request merged**
